server:
  port: 8084

spring:
  main:
    banner-mode: CONSOLE
  banner:
    location: banner.txt
  application:
    name: Location Query Service
  r2dbc:
    url: r2dbc:postgresql://locationpostgres.postgres.database.azure.com:5432/postgres?sslMode=require
    username: superuser@locationpostgres
    password: Admin123
    properties:
      sslMode: require

logging:
  level:
    io.r2dbc.postgresql.QUERY: INFO
    io.r2dbc.postgresql.PARAM: INFO




