apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
        - name: location-service
          image: locationpocregistry.azurecr.io/location-service:v1
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: location
spec:
  selector:
    app: location-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer
